openapi: 3.0.0
info:
  title: Identity Service
  version: 1.0.0
paths:
  /identity/requests:
    get:
      parameters:
        - name: gdid
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
        - name: rlimit
          in: query
          schema:
            type: integer
        - name: offset
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewIdentityRequest'
      responses:
        '200':
          description: Successful operation
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStatusRequest'
      responses:
        '200':
          description: Successful operation
  /identity/requests/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
  /identity/requests/validate/{nic}:
    get:
      parameters:
        - name: nic
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    NewIdentityRequest:
      type: object
      properties:
        initials_fullname:
          type: string
        fullname:
          type: string
        NIC:
          type: string
        gender:
          type: string
        contact_num:
          type: string
        email:
          type: string
        address:
          type: string
        DOB:
          type: string
          format: date-time
        gramasevaka_division:
          type: string
    UpdateStatusRequest:
      type: object
      properties:
        grama_nic:
          type: string
        request_id:
          type: string
        status:
          type: string
